### ISSUE TITLE
Investigate gem naming

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#104]
Let's check what names uses gem stash to store files on `gem push` and use same naming, now we generate random names on push.

**Comment by milkysoft** [comment]
@g4s8, `gem push` command indeed sends POST request to Ruby Server, which saves attached file into folder similar to ` ~/.gemstash/private/gems/y/a/r/yard_0_9_26-0449f68b65f6eda69d7c1b04abe79594/` for `yard-0.9.26.gem`. In this folder gem file is created together with properties and spec:

```
ls -l ~/.gemstash/private/gems/y/a/r/yard_0_9_26-0449f68b65f6eda69d7c1b04abe79594/
total 752
-rw-rw-r-- 1 zuoqin zuoqin 758272 Jul 21 11:03 gem
-rw-rw-r-- 1 zuoqin zuoqin     49 Jul 21 11:03 properties.yaml
-rw-rw-r-- 1 zuoqin zuoqin    448 Jul 21 11:03 spec
```

**Comment by g4s8** [comment]
> @g4s8, `gem push` command indeed sends POST request to Ruby Server, which saves attached file into folder similar to ` ~/.gemstash/private/gems/y/a/r/yard_0_9_26-0449f68b65f6eda69d7c1b04abe79594/` for `yard-0.9.26.gem`. In this folder gem file is created together with properties and spec:
> 
> ```
> ls -l ~/.gemstash/private/gems/y/a/r/yard_0_9_26-0449f68b65f6eda69d7c1b04abe79594/
> total 752
> -rw-rw-r-- 1 zuoqin zuoqin 758272 Jul 21 11:03 gem
> -rw-rw-r-- 1 zuoqin zuoqin     49 Jul 21 11:03 properties.yaml
> -rw-rw-r-- 1 zuoqin zuoqin    448 Jul 21 11:03 spec
> ```

@milkysoft what is the gem stash root dir in this example?
