### ISSUE TITLE
GemInfo.java:40-42: Gem Information implementation. The...

### ISSUE THREAD

**Issue by 0pdd** [artipie/gem-adapter#11]
The puzzle `32-d2ff0e89` from #32 has to be resolved: 

https://github.com/artipie/gem-adapter/blob/6188914211669540a343b2bfa5e09dcd739dfc6a/src/main/java/com/artipie/gem/GemInfo.java#L40-L42

The puzzle was created by @Sammers21 on 06-Apr-20. 

Estimate: 120 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `32-d2ff0e89` has disappeared from the source code, that's why I closed this issue.
