### ISSUE TITLE
Yaml format

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#122]
Produce YAML responses for gem info if requested: `GET /api/v1/gems/([\\w]+).yml`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#124](https://github.com/artipie/gem-adapter/issues/124) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#124](https://github.com/artipie/gem-adapter/issues/124) is solved here.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#137](https://github.com/artipie/gem-adapter/issues/137) is still not solved; solved: [#124](https://github.com/artipie/gem-adapter/issues/124).
