### ISSUE TITLE
JRuby internal usage

### ISSUE THREAD

**Issue by Sammers21** [artipie/gem-adapter#13]
There are a few reasons how internal usage of JRuby can be useful:

1. Ruby has own serialization approach. All the metadata files serialized in the given format and there is no Java-based parser. With JRuby the deserialization task becomes fairly simple. An example:

![image](https://user-images.githubusercontent.com/16746106/78950927-f8910680-7ad8-11ea-8207-c941dc0ef05a.png)

2. Metadata generation can be reused. As [RubyGem Index Internals](https://blog.packagecloud.io/eng/2015/12/15/rubygem-index-internals/) mentions, Ruby standard library includes `Gem::` package with anything you need for metadata generation.

3. JRuby is easily embeddable([read this](https://github.com/jruby/jruby/wiki/DirectJRubyEmbedding)). All you need is just 25mb jar from maven: 

![image](https://user-images.githubusercontent.com/16746106/78951369-91745180-7ada-11ea-87b9-6e04b9ea5ec9.png)

That is why I'd like to suggest to use JRuby for the necessary parts of the module.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@9452952fc9d1, thread: pool-936-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#13: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#13, Action: `opened`

**Comment by g4s8** [comment]
@Sammers21 ok, let's implement gem artifacts parser for metadata generator using jruby

**Comment by 0pdd** [comment]
@Sammers21 the puzzle [#15](https://github.com/artipie/gem-adapter/issues/15) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#13` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@Sammers21 the only puzzle [#15](https://github.com/artipie/gem-adapter/issues/15) is solved here.
