### ISSUE TITLE
GemSlice.java:46-49: Initialize on first request....

### ISSUE THREAD

**Issue by 0pdd** [artipie/gem-adapter#15]
The puzzle `13-4aa56782` from #13 has to be resolved: 

https://github.com/artipie/gem-adapter/blob/26af0b4587ecbbc7702d1c124e8c6bc9cb78cb34/src/main/java/com/artipie/gem/GemSlice.java#L46-L49

The puzzle was created by @Sammers21 on 10-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@cf6a468ba0d0, thread: pool-792-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#15: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53.1](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#15, Action: `opened`

**Comment by 0pdd** [comment]
The puzzle `13-4aa56782` has disappeared from the source code, that's why I closed this issue.
