### ISSUE TITLE
jruby-complete on which gems-adapter depends involves high-risk licenses.

### ISSUE THREAD

**Issue by tangjun-npm** [artipie/gem-adapter#205]
jruby-complete on which gems-adapter depends involves high-risk licenses.

**Comment by olenagerasimova** [comment]
@tangjun-npm hello again, I've taken a look into jruby-complete licenses. Jruby is distributed under three licenses - EPL 2.0, GPL 2.0 and LGPL 2.1. Normally, when the product distributed under [several conditions](https://en.wikipedia.org/wiki/Multi-licensing), it means, that the recipients can simply choose any condition they like. Here is the [confirmation](https://github.com/jruby/jruby/issues/6470). EPL is not in the list of high risk licenses, so you simply choose it.
