### ISSUE TITLE
SubmitGem.rb:38-40: Sync generated indexes with Storage....

### ISSUE THREAD

**Issue by 0pdd** [artipie/gem-adapter#25]
The puzzle `9-d0d317ad` from #9 has to be resolved: 

https://github.com/artipie/gem-adapter/blob/8ac1d79454cfb4f865705467889604cd1fa8fb79/src/main/ruby/SubmitGem.rb#L38-L40

The puzzle was created by @g4s8 on 22-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#30](https://github.com/artipie/gem-adapter/issues/30) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `9-d0d317ad` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#30](https://github.com/artipie/gem-adapter/issues/30) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#25` is not assigned, can't get performer
