### ISSUE TITLE
Gem API service

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#3]
Add API stubs for Ruby gem service/registry. Let's start with API documentation in the readme file.

**Comment by 0crat** [comment]
The job [#3](https://github.com/artipie/gem-adapter/issues/3) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/0d03d833-dfb4-4690-9874-ab3462880f3f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.1`

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.2`

**Comment by 0crat** [comment]
The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#3](https://github.com/artipie/gem-adapter/issues/3), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#3](https://github.com/artipie/gem-adapter/issues/3) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/817f447a-a4a7-45d5-848d-877785a081d1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @Sammers21

**Comment by g4s8** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/artipie/gem-adapter/issues/3#issuecomment-607845778))

@g4s8 Job `gh:artipie/gem-adapter#3` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat assign @Sammers21  ([here](https://github.com/artipie/gem-adapter/issues/3#issuecomment-607845660))

@g4s8 The job [#3](https://github.com/artipie/gem-adapter/issues/3) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e7790a14-4764-4b85-aed6-76a84e747ddd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by Sammers21** [comment]
@g4s8, can you fix that?

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@Sammers21 there are build failure:
```
+ '[' '!' -d ./lib ']'
+ gem fetch builder
Downloaded builder-3.2.4
++ ls
++ grep builder-3.2.4.gem
++ awk '{print $NF}'
+ BUILDER_GEM_FILE=builder-3.2.4.gem
+ GEM_PATH=lib
+ GEM_HOME=lib
+ ruby -S gem install ./builder-3.2.4.gem
ERROR:  While executing gem ... (Gem::DocumentError)
    RDoc is not installed: cannot load such file -- rdoc/rdoc
Successfully installed builder-3.2.4
[1;31mERRORm] Command execution failed.
1;31morg.apache.commons.exec.ExecuteExceptionm: 1;31mProcess exited with an error: 1 (Exit value: 1)m
    1matm org.apache.commons.exec.DefaultExecutor.executeInternal (1mDefaultExecutor.java:404m)
    1matm org.apache.commons.exec.DefaultExecutor.execute (1mDefaultExecutor.java:166m)
    1matm org.codehaus.mojo.exec.ExecMojo.executeCommandLine (1mExecMojo.java:804m)
    1matm org.codehaus.mojo.exec.ExecMojo.executeCommandLine (1mExecMojo.java:751m)
    1matm org.codehaus.mojo.exec.ExecMojo.execute (1mExecMojo.java:313m)
    1matm org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (1mDefaultBuildPluginManager.java:137m)
    1matm org.apache.maven.lifecycle.internal.MojoExecutor.execute (1mMojoExecutor.java:210m)
    1matm org.apache.maven.lifecycle.internal.MojoExecutor.execute (1mMojoExecutor.java:156m)
    1matm org.apache.maven.lifecycle.internal.MojoExecutor.execute (1mMojoExecutor.java:148m)
    1matm org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (1mLifecycleModuleBuilder.java:117m)
    1matm org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (1mLifecycleModuleBuilder.java:81m)
    1matm org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (1mSingleThreadedBuilder.java:56m)
    1matm org.apache.maven.lifecycle.internal.LifecycleStarter.execute (1mLifecycleStarter.java:128m)
    1matm org.apache.maven.DefaultMaven.doExecute (1mDefaultMaven.java:305m)
    1matm org.apache.maven.DefaultMaven.doExecute (1mDefaultMaven.java:192m)
    1matm org.apache.maven.DefaultMaven.execute (1mDefaultMaven.java:105m)
    1matm org.apache.maven.cli.MavenCli.execute (1mMavenCli.java:956m)
    1matm org.apache.maven.cli.MavenCli.doMain (1mMavenCli.java:288m)
    1matm org.apache.maven.cli.MavenCli.main (1mMavenCli.java:192m)
    1matm jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (1mNative Methodm)
    1matm jdk.internal.reflect.NativeMethodAccessorImpl.invoke (1mNativeMethodAccessorImpl.java:62m)
    1matm jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (1mDelegatingMethodAccessorImpl.java:43m)
    1matm java.lang.reflect.Method.invoke (1mMethod.java:566m)
    1matm org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (1mLauncher.java:282m)
    1matm org.codehaus.plexus.classworlds.launcher.Launcher.launch (1mLauncher.java:225m)
    1matm org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (1mLauncher.java:406m)
    1matm org.codehaus.plexus.classworlds.launcher.Launcher.main (1mLauncher.java:347m)
[1;34mINFOm] 1m------------------------------------------------------------------------m
[1;34mINFOm] 1;31mBUILD FAILUREm
[1;34mINFOm] 1m------------------------------------------------------------------------m
[1;34mINFOm] Total time:  01:10 min
[1;34mINFOm] Finished at: 2020-04-29T15:33:22Z
[1;34mINFOm] 1m------------------------------------------------------------------------m
```

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.3`

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#3` is not assigned, can't get performer
