### ISSUE TITLE
GemSlice.java:99-102: Use underlying storage. Currency,...

### ISSUE THREAD

**Issue by 0pdd** [artipie/gem-adapter#30]
The puzzle `25-b18eefce` from #25 has to be resolved: 

https://github.com/artipie/gem-adapter/blob/2c45b3c10a11f4f5fd6d9a4a4557f031d0a04b3a/src/main/java/com/artipie/gem/GemSlice.java#L99-L102

The puzzle was created by @Sammers21 on 29-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-566-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#30: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53.13](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#30, Action: `opened`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-1222-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.13](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#30, Action: `created`

**Comment by 0pdd** [comment]
The puzzle `25-b18eefce` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#30` is not assigned, can't get performer
