### ISSUE TITLE
Own version of indexer

### ISSUE THREAD

**Issue by Sammers21** [artipie/gem-adapter#40]
`Gem::Indexer`(currently used) stores metadata files locally, we need to have an own version which would store files in ASTO based storage.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@1141192d-e349-458f-8a77-e0fe31931131, thread: pool-761-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#40: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53.14](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#40, Action: `opened`

**Comment by 0crat** [comment]
The job [#40](https://github.com/artipie/gem-adapter/issues/40) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d90859d6-64bf-4fbb-a0b3-2d14f8397658); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@g4s8 we need to make sure that problem reporter and problem solver are two different persons

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by g4s8** [comment]
@rultor release, tag=`0.1.4`
