### ISSUE TITLE
Adapt AstoIndexer to generate files in storage

### ISSUE THREAD

**Issue by 0pdd** [artipie/gem-adapter#42]
The puzzle `9-59a54dc4` from #9 has to be resolved: 

https://github.com/artipie/gem-adapter/blob/890210fa1ed53ed345e99a2f1b6653630b6624df/src/main/ruby/AstoIndexer.rb#L22-L24

The puzzle was created by @Sammers21 on 08-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@47be01ee-43c3-4083-893b-28d1d64d4ea7, thread: pool-2214-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#42: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53.14](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#42, Action: `opened`

**Comment by 0pdd** [comment]
The puzzle `9-59a54dc4` has disappeared from the source code, that's why I closed this issue.
