### ISSUE TITLE
Bidirectional storage syncronization

### ISSUE THREAD

**Issue by Sammers21** [artipie/gem-adapter#43]
Now only locally generated files are copied into underlying storage without checking for updates, which is bad in a numerous amount of cases. 

The suggestion is to perform synchronization in both directions and synchronize the only often changing(the specs) and newly created files.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ae73ab37-41ee-4e38-af1d-a3b0f49d9fc0, thread: pool-97-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/gem-adapter#43: @g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
```

[0.53.14](https://github.com/zerocracy/farm): Issue: artipie/gem-adapter#43, Action: `opened`

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#43` is not assigned, can't get performer
