### ISSUE TITLE
Gem doesn't support authorization

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#45]
Gem adapter should support authorization mechanisms as other repositories. Main slice entry point has to accept `Permissions` and `Authentication` objects and use them to construct `SliceAuth` wrapper (see `MavenSlice` or `FilesSlice` for example).
If gem uses HTTP basic authentication, then standard implementation `BasicIdentities` from `artipie/http` module can be used. Otherwise, we have to implement custom authentication implementation in this module.

**Comment by 0crat** [comment]
The job [#45](https://github.com/artipie/gem-adapter/issues/45) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4c8f52ea-dce1-4b4e-a08c-9c4aa3a6b1a4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/gem-adapter/issues/45#issuecomment-642599836))

@g4s8 Job `gh:artipie/gem-adapter#45` is not assigned, can't get performer

**Comment by g4s8** [comment]
@Sammers21 can you please describe what API is needed for Gem repo authentication?

**Comment by Sammers21** [comment]
@g4s8, 
![image](https://user-images.githubusercontent.com/16746106/90408286-50a3cf00-e0b0-11ea-82f7-266062081af0.png)
https://guides.rubygems.org/rubygems-org-api/

**Comment by Sammers21** [comment]
@rultor, release tag=`0.3`

**Comment by Sammers21** [comment]
@yegor256, can you please change something in `.rultor.yaml` file so I can release a new version?

> > @rultor, release tag=`0.3`
> 
> @Sammers21 @g4s8 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/23069-677471395) (spent 16s)
> 
> ```
> + set -e
> + set -o pipefail
> ++ dirname ./run.sh
> + cd .
> + echo 11191
> + echo '1.69.1 839260fab'
> 1.69.1 839260fab
> + date
> Thu Aug 20 10:59:36 CEST 2020
> + uptime
>  10:59:36 up 308 days,  7:08,  0 users,  load average: 4.57, 4.64, 4.58
> + cat
> The last commit at .rultor.yml in artipie/gem-adapter is not verified, that's why assets are not permitted to use in yegor256/artipie-keys
> + exit -1
> 'cid' file is absent, container wasn't started correctly
> ```

**Comment by olegmoz** [comment]
@rultor release, tag=`0.3`

**Comment by olegmoz** [comment]
@Sammers21 please try again to release as you are an architect in `.rultor`

**Comment by Sammers21** [comment]
@rultor release, tag=`0.3`
