### ISSUE TITLE
Gems are not available for download after an upload

### ISSUE THREAD

**Issue by Sammers21** [artipie/gem-adapter#49]
The reason why gems are not available for download is that gems are named randomly and not synced with asto. 

The current gem proof demonstrate the error:
https://github.com/artipie/artipie/runs/894462378?check_suite_focus=true#step:4:55

PRs:
* [x] - #50 merged
* [x] - #51 merged

**Comment by Sammers21** [comment]
@g4s8, with #50 and #51, the gem proof at Artipie examples will pass, just checked it.

**Comment by g4s8** [comment]
@rultor release, tag=`0.2.2`

**Comment by g4s8** [comment]
@Sammers21 both PRs were merged, releasing a new version now

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
