### ISSUE TITLE
Gem build is failing

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#54]
Release is failing with this error message: https://github.com/artipie/gem-adapter/issues/52#issuecomment-674041928

**Comment by Sammers21** [comment]
@g4s8, i have no idea on how to reproduce the error. I suggest you fix it yourself.

**Comment by Sammers21** [comment]
@0crat refuse

**Comment by Sammers21** [comment]
So let me have the access to the `release` command so I can at least try to fix the error.

**Comment by Sammers21** [comment]
@g4s8, I've found out the error source. Artipie central has corrupted jars. I would suggest disabling Artpie central for now.

**Comment by g4s8** [comment]
@Sammers21 yes, the problem is in Maven proxy repository with corrupted cache after unexpected shutdown. Latest ppom doesn't have remote for Artipie-central proxy, only for private Maven repo.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/gem-adapter/issues/54#issuecomment-674735544))

@Sammers21 The user @sammers21[/z](https://www.0crat.com/u/sammers21) resigned from [#54](https://github.com/artipie/gem-adapter/issues/54), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/gem-adapter#54` is not assigned, can't get performer
