### ISSUE TITLE
Support Basic authentication

### ISSUE THREAD

**Issue by genryxy** [artipie/gem-adapter#81]
It would be good to support `Basic` authentication for Gem to install passing credentials in the url. To do this, you need to modify the method `GemApiKeyIdentities#user`

**Comment by genryxy** [comment]
@olegmoz could you please release a new version

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5.2`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.5.3`
