### ISSUE TITLE
Remove deprecated auth classes

### ISSUE THREAD

**Issue by genryxy** [artipie/gem-adapter#83]
Now in `GemApiKeyIdentities`, `ApiKeySlice`, `GemSlice` suppress warnings annotations are used for deprecation because `com.artipie.http` module was updated from 0.16.2 to 0.17.1 (see #82). So, these annotations should be removed.

**Comment by genryxy** [comment]
@olegmoz  could you please release `0.6` version of Gem because here is exception with index out of bound in class that is deprecated https://github.com/genryxy/artipie/runs/1619140634#step:4:44 Probably it will help to fix Gem proof.

**Comment by olegmoz** [comment]
@rultor release, tag=`0.6`
