### ISSUE TITLE
Implement `GemInfo` slice

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/gem-adapter#85]
Let's properly implement `GemInfo` slice provide information by json or yaml from request:
 - [x] HTTP `Slice` implementation for Gem info #94
 - [ ] SDK method for producing Gem info data in valid format

**Comment by g4s8** [comment]
Related: #11

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#101](https://github.com/artipie/gem-adapter/issues/101) is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#101](https://github.com/artipie/gem-adapter/issues/101) is solved here.
