### ISSUE TITLE
Gem SDK

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#89]
Introduce Gem repository SDK class to work with Gem data and generate metadata. It should encapsulate `Storage` insterface from `com.artipie.asto` and provides methods to update metadata for single package or batch update for packages:
```java
class Gem {
  private final Storage storage;

  public Gem(Storage storages) {
    this.storage = storage;
  }

  public CompletionStage<Void> batchUpdate(Key location) {
    // implement logic here
  }
}
```

**Comment by Sammers21** [comment]
There is no explanation for what you need.

**Comment by g4s8** [comment]
Done in #91
