### ISSUE TITLE
Rewrite slice implementation from ruby to java

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#90]
Remove existing Ruby files and implement `Slice` on Java using `com.artipie.http` packages, reuse `Gem` SDK implementation for Gem index updates instead of built-in scripts. Keep existing integration tests to verify that new implementation works find as HTTP repository.

**Comment by milkysoft** [comment]
@g4s8 ,
```
    public Response response(String line, Iterable<Entry<String, String>> headers, Publisher<ByteBuffer> body) {
        return new AsyncResponse(
            // Save attached gem file into storage
            this.storage.save(new Key.From("asdasd"), new ContentWithSize(body, headers))
                // Create metadata for newly saved gem
                .thenCompose(none -> this.gem.batchUpdate(Key.ROOT))
                // Return OK result
                .thenApply(none -> new RsWithStatus(RsStatus.CREATED))
        );
    }
```
does not work well with unit  test:
```
        MatcherAssert.assertThat(
            AuthTest.postWithBasicAuth(true),
            new RsHasStatus(RsStatus.OK)
        );
```
with error:
```
Expected: <OK>
     but: was <(AsyncResponse: java.util.concurrent.CompletableFuture@d9345cd[Completed normally])>
```

thus AsynResponse replaced with 
```
final CompletableFuture<Void> res = ....
res.join();
return new RsWithStatus(RsStatus.OK);
```

**Comment by g4s8** [comment]
> @g4s8 ,
> 
> ```
>     public Response response(String line, Iterable<Entry<String, String>> headers, Publisher<ByteBuffer> body) {
>         return new AsyncResponse(
>             // Save attached gem file into storage
>             this.storage.save(new Key.From("asdasd"), new ContentWithSize(body, headers))
>                 // Create metadata for newly saved gem
>                 .thenCompose(none -> this.gem.batchUpdate(Key.ROOT))
>                 // Return OK result
>                 .thenApply(none -> new RsWithStatus(RsStatus.CREATED))
>         );
>     }
> ```
> 
> does not work well with unit test:
> 
> ```
>         MatcherAssert.assertThat(
>             AuthTest.postWithBasicAuth(true),
>             new RsHasStatus(RsStatus.OK)
>         );
> ```
> 
> with error:
> 
> ```
> Expected: <OK>
>      but: was <(AsyncResponse: java.util.concurrent.CompletableFuture@d9345cd[Completed normally])>
> ```
> 
> thus AsynResponse replaced with
> 
> ```
> final CompletableFuture<Void> res = ....
> res.join();
> return new RsWithStatus(RsStatus.OK);
> ```

@milkysoft please don't use blocking calls such as `.join()` in production code, it's OK **only** in tests. Also, the test may require some fixes, e.g. assertion that status is 201, not 200

**Comment by milkysoft** [comment]
@g4s8 , blocking calls removed with latest commit
