### ISSUE TITLE
Gem dependencies API

### ISSUE THREAD

**Issue by g4s8** [artipie/gem-adapter#97]
Let's investigate what is `/api/v1/dependencies` API and create an SDK method to cover this API request.

**Comment by milkysoft** [comment]
We should find Ruby command to return the same info as `gem dependecy XXXX`:

```
gem dependency gviz
Gem gviz-0.3.5
  bundler (~> 1.5, development)
  rake (>= 0, development)
  rspec (~> 2.1, development)
  thor (>= 0)
```

The command works only for installed gems, cannot extract dependency info for arbitrary gem file

**Comment by milkysoft** [comment]
Among all other info, `Gem::Package.new('src/test/resources/gviz-0.3.5.gem').spec` returns required dependencies for arbitrary gem file
```
=> #<Gem::Specification:0x000055d16d06a330 @cache_file=nil, @original_platform="ruby", @installed_by_version=nil, @autorequire=nil, @description="Ruby's interface of graphviz", @email=["postagie@gmail.com"], @homepage="https://github.com/melborne/Gviz", @name="gviz", @post_install_message=nil, @rubyforge_project=nil, @signing_key=nil, @summary="Ruby's interface of graphviz. It generate a dot file with simple ruby's syntax.", @version=#<Gem::Version "0.3.5">, @authors=["kyoendo"], @bindir="bin", @cert_chain=[], @date=2015-04-03 00:00:00 UTC, @dependencies=[<Gem::Dependency type=:development name="rspec" requirements="~> 2.1">, <Gem::Dependency type=:development name="bundler" requirements="~> 1.5">, <Gem::Dependency type=:development name="rake" requirements=">= 0">, <Gem::Dependency type=:runtime name="thor" requirements=">= 0">], @executables=["gviz"], @extensions=[], @extra_rdoc_files=[], @files=[".gitignore", ".travis.yml", "Gemfile", "LICENSE.txt", "README.md", "Rakefile", "bin/gviz", "examples/arrows.rb", "examples/colors.rb", "examples/examples.rb", "examples/sample1.png", "examples/sample2.png", "examples/sample3.png", "examples/sample4.png", "examples/shapes.rb", "gviz.gemspec", "lib/gviz.rb", "lib/gviz/command.rb", "lib/gviz/core.rb", "lib/gviz/draw.rb", "lib/gviz/edge.rb", "lib/gviz/graphviz_attrs.rb", "lib/gviz/node.rb", "lib/gviz/system_extension.rb", "lib/gviz/version.rb", "spec/fixtures/graph.ru", "spec/gviz_command_spec.rb", "spec/gviz_draw_spec.rb", "spec/gviz_edge_spec.rb", "spec/gviz_node_spec.rb", "spec/gviz_spec.rb", "spec/spec_helper.rb", "spec/system_extension_spec.rb"], @licenses=[], @metadata={}, @platform="ruby", @rdoc_options=[], @require_paths=["lib"], @required_ruby_version=#<Gem::Requirement:0x000055d16cfa1e08 @requirements=[[">=", #<Gem::Version "2.0.0">]]>, @required_rubygems_version=#<Gem::Requirement:0x000055d16cfb2aa0 @requirements=[[">=", #<Gem::Version "0">]]>, @requirements=[], @rubygems_version="2.4.5", @specification_version=4, @test_files=["spec/fixtures/graph.ru", "spec/gviz_command_spec.rb", "spec/gviz_draw_spec.rb", "spec/gviz_edge_spec.rb", "spec/gviz_node_spec.rb", "spec/gviz_spec.rb", "spec/spec_helper.rb", "spec/system_extension_spec.rb"], @new_platform="ruby", @full_name=nil gviz-0.3.5>

**Comment by g4s8** [comment]
@milkysoft does any documentation exist for this API endpoint? What this `/api/v1/dependencies` returns exactly?

**Comment by milkysoft** [comment]
@g4s8 , yes, documentation regarding `/api/v1/dependencies` is [very clear](https://guides.rubygems.org/rubygems-org-api/):
```
ruby -ropen-uri -rpp -e \
  'pp Marshal.load(open("https://rubygems.org/api/v1/dependencies?gems=rails,thor"))'

[{:platform=>"ruby",
  :dependencies=>
   [["bundler", "~> 1.0"],
    ["railties", "= 3.0.3"],
    ["actionmailer", "= 3.0.3"],
    ["activeresource", "= 3.0.3"],
    ["activerecord", "= 3.0.3"],
    ["actionpack", "= 3.0.3"],
    ["activesupport", "= 3.0.3"]],
  :name=>"rails",
  :number=>"3.0.3"},
...
{:number=>"0.9.9", :platform=>"ruby", :dependencies=>[], :name=>"thor"}]
```

**Comment by g4s8** [comment]
@milkysoft  I see, it says:
> Returns a marshalled array of hashes for all versions of given gems. Each hash contains a gem version with its dependencies making this useful for resolving dependencies.

So we need to find a way to extract this information from gem files or metadata

**Comment by milkysoft** [comment]
@g4s8, I confirm the information could be extracted from arbitrary gem file. Taking into account, that it is supposed to NOT transfer gem file in GET request, so we will return information only for installed gem, coping them as previously from existing storage

**Comment by g4s8** [comment]
> @g4s8, I confirm the information could be extracted from arbitrary gem file. Taking into account, that it is supposed to NOT transfer gem file in GET request, so we will return information only for installed gem, coping them as previously from existing storage

@milkysoft I don't think the install operation is acceptable for repository manager service, we need to find a way to extract it from gem file or metadata without installations.

**Comment by milkysoft** [comment]
@g4s8, I confirm the information could be extracted from arbitrary gem file without installation.

**Comment by milkysoft** [comment]
`gem dependency gviz -r` sends the following requests to `gem sources` listed remote server:
1. GET /latest_specs.4.8.gz
2. GET /quick/Marshal.4.8/gviz-0.3.5.gemspec.rz

**Comment by g4s8** [comment]
> `gem dependency gviz -r` sends the following requests to `gem sources` listed remote server:
> 
>     1. GET /latest_specs.4.8.gz
> 
>     2. GET /quick/Marshal.4.8/gviz-0.3.5.gemspec.rz

@milkysoft please check this code, the gem library requests dependencies API here: https://github.com/rubygems/gems/blob/77cad26e101ba70e6cdb3ba2ac51139bdc5a0648/lib/gems/client.rb#L292

**Comment by milkysoft** [comment]
@g4s8 , I confirm we are using exactly the algorithm above. I am trying to implement required route, adding to GemSlice:
```
  new RtRulePath(
      new RtRule.All(
          new ByMethodsRule(RqMethod.GET),
          new RtRule.ByPath("/latest_specs.4.8.gz")
      ),
      new GemInfoClass(storage, new Gem(storage))
  ),
```
and it responds with `Key latest_specs.4.8.gz not found` when `curl http://host.testcontainers.internal:36047/latest_specs.4.8.gz`. My question is, can we implement root paths or only `/api/v1` are available?

**Comment by milkysoft** [comment]
@g4s8, we have successfully implemented `gem dependency` functionality:

1. Log to ruby container, add `gem sources` pointing to container, remove default with `gem sources -r https://rubygems.org/`:
```
root@0df12db71df8:/home# gem sources -a http://host.testcontainers.internal:33461/
http://host.testcontainers.internal:33461/ added to sources
root@0df12db71df8:/home# gem sources
*** CURRENT SOURCES ***

http://host.testcontainers.internal:33461/
```
2. For thor gem we did not upload it with test, so result is negative:
```
root@0df12db71df8:/home# gem dependency thor -r
No gems found matching thor (>= 0)
```
3. For gviz gem result is successful:
```
root@0df12db71df8:/home# gem dependency gviz -r
Gem gviz-0.3.5
  bundler (~> 1.5, development)
  rake (>= 0, development)
  rspec (~> 2.1, development)
  thor (>= 0)
```
4. On server side the following requests were implemented:
```
GET /specs.4.8.gz HTTP_1_1

GET /latest_specs.4.8.gz HTTP_1_1

GET /quick/Marshal.4.8/gviz-0.3.5.gemspec.rz HTTP_1_1
```
5. Unfortunately, `gem dependency` does not invoke `/api/v1/dependencies?gems=gviz" route

**Comment by g4s8** [comment]
> @g4s8, we have successfully implemented `gem dependency` functionality:
> 
>     1. Log to ruby container, add `gem sources` pointing to container, remove default with `gem sources -r https://rubygems.org/`:
> 
> 
> ```
> root@0df12db71df8:/home# gem sources -a http://host.testcontainers.internal:33461/
> http://host.testcontainers.internal:33461/ added to sources
> root@0df12db71df8:/home# gem sources
> *** CURRENT SOURCES ***
> 
> http://host.testcontainers.internal:33461/
> ```
> 
>     1. For **thor** gem we did not upload it with test, so result is negative:
> 
> 
> ```
> root@0df12db71df8:/home# gem dependency thor -r
> No gems found matching thor (>= 0)
> ```
> 
>     1. For **gviz** gem result is successful:
> 
> 
> ```
> root@0df12db71df8:/home# gem dependency gviz -r
> Gem gviz-0.3.5
>   bundler (~> 1.5, development)
>   rake (>= 0, development)
>   rspec (~> 2.1, development)
>   thor (>= 0)
> ```
> 
>     1. On server side the following requests were implemented:
> 
> 
> ```
> GET /specs.4.8.gz HTTP_1_1
> 
> GET /latest_specs.4.8.gz HTTP_1_1
> 
> GET /quick/Marshal.4.8/gviz-0.3.5.gemspec.rz HTTP_1_1
> ```
> 
>     1. Unfortunately, `gem dependency` does not invoke `/api/v1/dependencies?gems=gviz" route

@milkysoft we need to find what command of `gem` uses `/dependencies` API first to verify it, please see my previous message with a link to source code https://github.com/artipie/gem-adapter/issues/97#issuecomment-869585450

**Comment by milkysoft** [comment]
@g4s8 , tested `bundle install` command, still no request for `/v1/dependencies`:

1. Gemfile:
```
# frozen_string_literal: true

source "http://host.testcontainers.internal:44995"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'gviz', '0.3.5'
```
2. `bundle install`:
```
Fetching gem metadata from http://host.testcontainers.internal:44995/..
Resolving dependencies...
Using bundler 2.2.21
Fetching thor 1.1.0
Installing thor 1.1.0
Fetching gviz 0.3.5
Installing gviz 0.3.5
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
3. Requests on server side:
```
Host: http://host.testcontainers.internal:44995, API_KEY: dXNyOnB3ZA==
GET /versions HTTP_1_1

GET /info/gviz HTTP_1_1

GET /info/thor HTTP_1_1

GET /gems/thor-1.1.0.gem HTTP_1_1

GET /gems/gviz-0.3.5.gem HTTP_1_1
```
All these routes added to the Pull request

**Comment by milkysoft** [comment]
Only gviz dependency reply:


![001](https://user-images.githubusercontent.com/13083981/124764374-8c9c8880-df3d-11eb-974a-4324500dfa13.png)

**Comment by milkysoft** [comment]
Finally Custom Ruby Server calls /api/v1/dependencies on `bundle install`:

<img width="767" alt="Screenshot 2021-07-13 at 12 14 41" src="https://user-images.githubusercontent.com/13083981/125426066-4a697589-45e5-45ea-bba9-ab7f7deb0641.png">
